apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app-ns
data:
  BLOG_TITLE: "My Blog"
  ANALYTICS_MODE: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: app-ns
type: Opaque
data:
  JWT_KEY: w7k+g1J9TrmP8XwKq1ZNm9pDfZRp7nEd2URj3oK5yLQ=