apiVersion: v1
kind: Namespace
metadata:
  name: app-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
  namespace: app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: usman134/blog:latest
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: blog-svc
  namespace: app-ns
spec:
  type: ClusterIP
  selector:
    app: blog
  ports:
  - port: 80
    targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: usman134/auth:latest
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: app-ns
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
  - port: 80
    targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
  namespace: app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics
        image: usman134/analytics:latest
        ports:
        - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-svc
  namespace: app-ns
spec:
  type: ClusterIP
  selector:
    app: analytics
  ports:
  - port: 80
    targetPort: 3003