name: CI/CD
on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push images
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/blog:${{ github.sha }} -f blog/Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/blog:${{ github.sha }}
        # repeat for auth & analytics

    - name: Deploy to cluster
      uses: azure/k8s-deploy@v2
      with:
        manifests: infra/*.yaml
        images: |
          ${{ secrets.DOCKERHUB_USERNAME }}/blog:${{ github.sha }}
          ${{ secrets.DOCKERHUB_USERNAME }}/auth:${{ github.sha }}
          ${{ secrets.DOCKERHUB_USERNAME }}/analytics:${{ github.sha }}
        kubeconfig: ${{ secrets.KUBECONFIG }}
